name: Download & Release Youtube Playlists

on:
  pull_request:
  push:
    tags:
      - "*.*.*"

jobs:

  build:
    name: Build
    #runs-on: ubuntu-latest
    runs-on: self-hosted #opensuse-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'

      - name: Install PIGZ
        run: |
          #sudo apt-get update -y
          #sudo apt-get install -y pigz
          sudo zypper update -y
          sudo zypper install -y pigz

      - name: Install FFMEG
        run: |
          #sudo apt-get install -y ffmpeg
          sudo zypper install -y ffmpeg-4

      - name: Install FFMEG
        run: |
          #sudo apt-get install -y python3
          sudo zypper install -y python3

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
        
      - name: Get youtube-dl
        run: |
          sudo pip3 install --upgrade --force-reinstall "git+https://github.com/ytdl-org/youtube-dl.git"
      
      - name: Go Build
        run: |
          git config --global --add safe.directory "$(pwd)"
          git tag "$(date '+%Y%m%d.%H%M%S')"
          go build -o main -v .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:  ${{ github.ref }}
          body_path: ./resource/playlist-list.csv
          release_name: New Youtube Playlist ${{ github.ref }}
          draft: false
          prerelease: false


      - name: Go Run
        run: |
          ./main

      - name: Upload Release Assets
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./*.tar.gz

      - name: Commit Removed Lines From List Of Playlist
        uses: EndBug/add-and-commit@v5
        with:
          author_name: AutoBot
          author_email: hi@mrturkmen.com
          message: "[automated msg]: playlist doc updated with new release"
          branch: master
          add: "resource/*.csv"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
